### ISSUE TITLE
Max, could you keep the club spreadsheet updated whenever we add a new club?

### ISSUE THREAD

**Issue by jonleung** [hackedu/docs#29]
Feel free to refactor it and make it not terrible haha:

https://docs.google.com/spreadsheets/d/1ir-DGpLsU2-8VifomVR1XfRvoHyUIjz2rV5ab7CMDoc/edit#gid=0

**Comment by MaxWofford** [comment]
On it. I plan on getting everything synced Mon-Tues.

**Comment by zachlatta** [comment]
Can we close this issue?
