### ISSUE TITLE
Why do etherpads not wrap text when the line overflows? 

### ISSUE THREAD

**Issue by jonleung** [hackedu/docs#37]
It seems like beta.etherpad.com has a more updated version of the pad
See this http://mew.hackedu.us:7398/p/042015 vs https://beta.etherpad.org/p/wef

**Comment by zachlatta** [comment]
@jonleung both of those pads are empty.

**Comment by zachlatta** [comment]
![recorded](https://cloud.githubusercontent.com/assets/992248/7235464/3411d484-e743-11e4-910b-64c9adc9a617.gif)

**Comment by jonleung** [comment]
@zachlatta added the text back again

**Comment by zachlatta** [comment]
Still don't see the issue.

**Comment by MaxWofford** [comment]
These are the same when I test (chrome running on chromebook and chrome on android galaxy note 3)

**Comment by zachlatta** [comment]
Since neither @MaxWofford or I can reproduce this, going to close it.

**Comment by zachlatta** [comment]
Perhaps @jonleung could post a GIF showing what he means?
